### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by tom-heidenreich** [heidenreichgeorg/JSBalance#5]
Im Readme sollte nicht die Geschichte stehen (wenn man das unbedingt will, dann ein `History.md` machen). Im Readme sollte ein Projektbeschreibung sein (Und das am besen nicht alles **Fett**), vielleicht wie man die Website benutzt und vielleicht eine Dokumentation der API

**Comment by heidenreichgeorg** [comment]
split HISTORY.md from READ.md
will soon remove #4
